### ISSUE TITLE
bind_to 'private_ip' in Opsworks fails

### ISSUE THREAD

**Issue by ebeyrent** [sous-chefs/percona#347]
I'm using Opsworks to deploy Percona instances, and am setting the bind_to attribute in my recipe like this:

node.default['percona']['server']['bind_to'] = 'private_ip'

However, it's failing to find the 'find_private_ip' method:
## NoMethodError

undefined method `find_private_ip' for Percona::ConfigHelper:Module

Trace:

[2015-11-17T17:12:44+00:00] DEBUG: filtered backtrace of compile error: /var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:37:in `bind_to',/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/configure_server.rb:24:in`from_file',/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/server.rb:40:in `from_file',/var/lib/aws/opsworks/cache.stage2/cookbooks/fen-database-server/recipes/community.rb:45:in`from_file'
[2015-11-17T17:12:44+00:00] DEBUG: filtered backtrace of compile error: /var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:37:in `bind_to',/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/configure_server.rb:24:in`from_file',/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/server.rb:40:in `from_file',/var/lib/aws/opsworks/cache.stage2/cookbooks/fen-database-server/recipes/community.rb:45:in`from_file'
[2015-11-17T17:12:44+00:00] DEBUG: backtrace entry for compile error: '/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:37:in `bind_to''
[2015-11-17T17:12:44+00:00] DEBUG: Line number of compile error: '37'
# 
# Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/fen-database-server/recipes/community.rb
## NoMethodError

undefined method `find_private_ip' for Percona::ConfigHelper:Module
## Cookbook Trace:

/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:37:in `bind_to'
/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/configure_server.rb:24:in`from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/server.rb:40:in `from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/fen-database-server/recipes/community.rb:45:in`from_file'
## Relevant File Content:

/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:

30:  
31:    # Public: This module provides a helper method for binding to a given IP
32:    # address
33:    module ConfigHelper
34:      def bind_to(node, interface)
35:        case interface
36:        when "public_ip"  then find_public_ip(node)
37>>       when "private_ip" then find_private_ip(node)
38:        when "loopback"   then find_loopback_ip(node)
39:        else find_interface_ip(node, interface)
40:        end
41:      end
42:      module_function :bind_to
43:  
44:      private
45:  
46:      def find_public_ip(node)

[2015-11-17T17:12:44+00:00] DEBUG: Re-raising exception: NoMethodError - undefined method `find_private_ip' for Percona::ConfigHelper:Module
/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/libraries/config_helper.rb:37:in`bind_to'
/var/lib/aws/opsworks/cache.stage2/cookbooks/percona/recipes/configure_server.rb:24:in `from_file'

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
